title: Pavlo Kezlia blog
email: aacmerchant@gmail.com
description:
baseurl: "stendorth.github.io"
url: ""

github_username:  Stendorth

# Build settings
plugins:
  - jekyll-feed

sass:
 sass_dir: _sass
 style: compressed
